### ISSUE TITLE
Network subnet not being used

### ISSUE THREAD

**Issue by ProvJamesThurber** [Perimeter81-Public/terraform-provider-perimeter81#6]
The documentation indicates that the network nested schema allows for the network subnet to be set

https://registry.terraform.io/providers/Perimeter81-Public/perimeter81/latest/docs/resources/network#subnet

In testing the deployment of a network this is not being set and the subnet is defaulting to 10.22.0.0/16

Subsequent terraform applies attempt to update the network subnet in place and appear to complete but the subnet is not updated.

Using the API, the subnet for the network can be set upon network creation.

**Comment by xsvil** [comment]
I am having the same issue. After reviewing the module's code it seems no logic for assigning the subnet has been set, but only for reading it.
https://github.com/Perimeter81-Public/terraform-provider-perimeter81/blob/18995bd48ac2704e2ecfd93494148b244ea20e92/perimeter81/resource_network.go#L37

**Comment by MuhammeedAlaa** [comment]
Thank you guys for reporting the issue, we will fix it soon!

**Comment by MuhammeedAlaa** [comment]
Fixed in version 1.6.8
